ARG BASE="mumak:1.12.1"
FROM ${BASE}

COPY workloads /workloads

WORKDIR /root
RUN git clone https://github.com/DICL/CCEH

WORKDIR /root/CCEH/CCEH-PMDK
COPY docker/cceh.patch .
RUN git apply cceh.patch
RUN mkdir bin && make

WORKDIR /scripts
ENV LD_PRELOAD=$MUMAK_ROOT/tools/pmdk/src/debug/libpmem.so.1:$MUMAK_ROOT/tools/pmdk/src/debug/libpmemobj.so.1
